{% set version = "0.3" %}

package:
  name: qt_binder
  version: {{ version }}

source:
  fn: qt_binder-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/q/qt_binder/qt_binder-{{ version }}.tar.gz
  sha256: ce726282de4a2f2c3a97cb01bbd25bd6ad8a15a4fc0fa51997c96414b9d00017
  patches:
    # fix pyqt & python3 bugs: https://github.com/enthought/qt_binder/pull/48
    - py3_fixes.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  skip: True  # [py>36]  # no pyqt 4.11.* for Python 3.7

requirements:
  build:
    - python
    - pip
  run:
    - python
    - future  # [py2k]  needed for builtins as used in pyqt4 code from pyface
    - pyqt 4.11.*
    - traitsui
    - six

test:
  requires:
    - nose  # [not unix]
    - mock  # [not unix]
  imports:
    - qt_binder
    # importing the API requires X, so skip on unix
    - qt_binder.api  # [not unix]
  commands:
    - python -m nose qt_binder  # [not unix]

about:
  home: https://github.com/enthought/qt_binder
  license: BSD 3-clause
  summary: QtBinder thinly wraps Qt widgets with Traits

extra:
  recipe-maintainers:
    - grlee77
